networks:
  minimal-server:
    name: minimal-server_ldes-network

services:

  ldes-server:
    container_name: minimal-server_ldes-server
    image: ldes/ldes-server:3.6.1-SNAPSHOT
    environment:
      - SIS_DATA=/tmp
      - LDESSERVER_HOSTNAME=http://localhost:9003
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ldespostgresdb:5433/minimal-server
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - SPRING_BATCH_JDBC_INITIALIZESCHEMA=always
    volumes:
      - ./config/application.yml:/application.yml:ro
    ports:
      - 9003:80
    networks:
      - minimal-server
    depends_on:
      - ldespostgresdb
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://ldes-server:8080/actuator/health"]

  ldespostgresdb:
    container_name: ldespostgresdb
    image: postgres:latest
    environment:
      - POSTGRES_DB=minimal-server
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - 5433:5433
    networks:
      - minimal-server