# This is a pipeline for demonstrating how to setup a pipeline to follow a publicly available LDES as a Data Client
name: client-pipeline
description: "Replicates & synchronizes a LDES view and sends each member to a sink"
input:
  name: Ldio:LdesClient
  config:
    urls: 
      - https://telraam-api.net/ldes/observations

    sourceFormat: application/n-quads

# outputs:
#   - name: Ldio:HttpOut
#     config:
#     #   endpoint: http://server_sink-system:80/member  # Updated endpoint
#       rdf-writer:
#         content-type: application/n-triples

outputs:
  - name: Ldio:HttpOut
    config:
      endpoint: http://localhost:9007/member