networks:
  # basic-setup:
  #   name: basic-setup_ldes-network
  shared-network:
    external: true

services:

  ldes-postgresdb:
    container_name: basic-setup_ldes-postgresdb
    image: postgres:latest
    environment:
      - POSTGRES_DB=basic-setup
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    ports:
      - 5433:5433
    networks:
      # - basic-setup
      - shared-network

  ldes-server:
    container_name: basic-setup_ldes-server
    image: ldes/ldes-server:3.6.1-SNAPSHOT
    environment:
      - SERVER_PORT=80
      - SIS_DATA=/tmp
      - SERVER_SERVLET_CONTEXTPATH=/ldes
      - LDESSERVER_HOSTNAME=http://localhost:9003/ldes
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ldes-postgresdb:5432/basic-setup
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PWD}
      - SPRING_BATCH_JDBC_INITIALIZESCHEMA=always
    volumes:
      - ./server/application.yml:/application.yml:ro
    ports:
      - 9003:80
    networks:
      shared-network:
        aliases:
          - ldes-server
    depends_on:
      - ldes-postgresdb
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://ldes-server/ldes/actuator/health"]

  ldio-workbench:
    container_name: basic-setup_ldio-workbench
    image: ldes/ldi-orchestrator:2.9.0-SNAPSHOT
    environment:
      - SERVER_PORT=80
    volumes:
      - ./workbench/application.yml:/ldio/application.yml:ro
    ports:
      - 9005:80
    networks:
      # - basic-setup 
      - shared-network
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://ldio-workbench/actuator/health"]

  ldio-workbench-client:
    container_name: basic-client_ldio-workbench
    image: ldes/ldi-orchestrator:2.9.0-SNAPSHOT
    environment:
      - SERVER_PORT=80
    volumes:
      - ./clientworkbench/application.yml:/ldio/application.yml:ro
    
    ports:
      - 9006:80
    networks:
      # - basic-setup 
      - shared-network
    # healthcheck:
    #   test: ["CMD", "wget", "-qO-", "http://ldio-workbench/actuator/health"]

  sink-system:
    container_name: basic-client_sink-system
    image: ghcr.io/informatievlaanderen/test-message-sink:latest
    ports:
      - 9007:80
    networks:
      - shared-network
    environment:
      - MEMORY=true
      - MEMBER_TYPE=http://schema.aquafin.be/#Overstort

