apiVersion: v1
kind: Service
metadata:
  name: ldio-workbench-service
spec:
  selector:
    app: ldio-workbench
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 80
  type: LoadBalancer
